on: ["push", "pull_request"]

name: backend coverage

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: openssl
        run: |
          sudo apt-get update -y && sudo apt-get install -y openssl

      - name: npm install, test:coverage
        run: |
          cd backend
          npm install
          npx prisma migrate dev
          npm run test:coverage

      - name: lcov-reporter
        uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          lcov-file: ./backend/coverage/lcov.info
